'use client';

import { generateEmailWithChat, refineEmail } from '@/actions/ai-actions';
import { useActionState } from 'react';
import { useState, useEffect, useRef, useCallback } from 'react';
import {
  Mail,
  Loader2,
  Copy,
  ExternalLink,
  Scissors,
  Smile,
  Check,
  Sparkles,
} from 'lucide-react';
import { useFormStatus } from 'react-dom';
import { useSearchParams } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from '@/lib/utils';
import { BackButton } from '@/components/ui/back-button';
import { MarkdownRenderer } from '@/components/markdown-renderer';

const QUICK_CHIPS = [
  { id: 'authority', label: 'Behörde' },
  { id: 'boss', label: 'Chef' },
  { id: 'landlord', label: 'Vermieter' },
  { id: 'customer', label: 'Kunde' },
];

const LANGUAGES = [
  'Deutsch',
  'Englisch',
  'Türkisch',
  'Spanisch',
  'Französisch',
  'Italienisch',
] as const;

function parseResult(text: string): { subject: string; body: string } {
  const t = text?.trim() || '';
  const m = t.match(/^Betreff:\s*(.+?)(?:\n\n?|$)/i);
  if (m) {
    const subject = m[1]!.trim();
    const body = t.slice(m[0]!.length).trim();
    return { subject, body };
  }
  return { subject: 'E-Mail', body: t };
}

function buildFullText(subject: string, body: string): string {
  if (!body) return '';
  return subject ? `Betreff: ${subject}\n\n${body}` : body;
}

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <button
      type="submit"
      disabled={pending}
      className={cn(
        'w-full rounded-xl py-3.5 font-semibold text-white tracking-tight',
        'bg-gradient-to-r from-orange-500 to-pink-500 hover:from-orange-600 hover:to-pink-600',
        'disabled:opacity-50 disabled:cursor-not-allowed transition-all',
        'flex items-center justify-center gap-2 shadow-lg shadow-orange-500/25'
      )}
    >
      {pending ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin" />
          Verfasse E-Mail…
        </>
      ) : (
        <>
          <Sparkles className="w-4 h-4" />
          E-Mail verfassen ✨
        </>
      )}
    </button>
  );
}

export default function EmailPage() {
  const [state, formAction] = useActionState(generateEmailWithChat, null);
  const searchParams = useSearchParams();

  const [mode, setMode] = useState<'new' | 'reply'>('new');
  const [recipientRole, setRecipientRole] = useState<string>('');
  const [recipientName, setRecipientName] = useState('');
  const [recipientEmail, setRecipientEmail] = useState('');
  const [language, setLanguage] = useState('Deutsch');
  const [topic, setTopic] = useState('');
  const [receivedEmail, setReceivedEmail] = useState('');

  const [resultText, setResultText] = useState('');
  const [editSubject, setEditSubject] = useState('');
  const [editBody, setEditBody] = useState('');
  const [refineLoading, setRefineLoading] = useState<'shorten' | 'loosen' | 'grammar' | null>(null);
  const [toast, setToast] = useState<string | null>(null);

  const formRef = useRef<HTMLFormElement>(null);
  const autoGeneratedRef = useRef(false);

  const chain = searchParams.get('chain');
  const client = searchParams.get('client');
  const ref = searchParams.get('ref');
  const type = searchParams.get('type');

  useEffect(() => {
    if (chain === 'invoice' && client && ref && type && !autoGeneratedRef.current) {
      const prefill = `Sende dem Kunden '${client}' das Dokument '${ref}' (${type}). Bitte freundlich und professionell formulieren.`;
      setTopic(prefill);
      setRecipientRole('Kunde');
      autoGeneratedRef.current = true;
      setTimeout(() => {
        if (formRef.current) {
          const topicEl = formRef.current.querySelector('[name="topic"]') as HTMLTextAreaElement | null;
          if (topicEl) topicEl.value = prefill;
          formRef.current.requestSubmit();
        }
      }, 400);
    }
  }, [chain, client, ref, type]);

  const handleChipClick = (label: string) => {
    setRecipientRole(label);
  };

  useEffect(() => {
    if (state?.result && !state.error) {
      const isUpsell = state.result.includes('Premium') || state.result.includes('Freischalten');
      if (!isUpsell) {
        const { subject, body } = parseResult(state.result);
        setResultText(state.result);
        setEditSubject(subject);
        setEditBody(body);
      }
    }
  }, [state?.result, state?.error]);

  useEffect(() => {
    if (!toast) return;
    const t = setTimeout(() => setToast(null), 2500);
    return () => clearTimeout(t);
  }, [toast]);

  const syncResultFromEdits = useCallback(() => {
    const full = buildFullText(editSubject, editBody);
    setResultText(full);
  }, [editSubject, editBody]);

  const fullTextForCopy = resultText || buildFullText(editSubject, editBody);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(fullTextForCopy);
      setToast('In Zwischenablage kopiert!');
    } catch {
      setToast('Kopieren fehlgeschlagen.');
    }
  };

  const handleGmail = () => {
    const { subject, body } = parseResult(fullTextForCopy);
    const mailto = recipientEmail
      ? `mailto:${recipientEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
      : `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(mailto);
  };

  const handleRefine = async (kind: 'shorten' | 'loosen' | 'grammar') => {
    const text = fullTextForCopy;
    if (!text.trim()) return;
    setRefineLoading(kind);
    try {
      const res = await refineEmail(text, kind);
      if (res.error) {
        setToast(res.error);
        return;
      }
      if (res.result) {
        const { subject, body } = parseResult(res.result);
        setResultText(res.result);
        setEditSubject(subject);
        setEditBody(body);
        setToast('Text angepasst.');
      }
    } finally {
      setRefineLoading(null);
    }
  };

  return (
    <div className="flex flex-col mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8">
      <BackButton href="/dashboard" className="text-gray-600 hover:text-gray-900 mb-3 tracking-tight" />

      <div
        className={cn(
          'flex flex-col lg:flex-row border border-gray-200 rounded-2xl overflow-hidden bg-white shadow-sm',
          'h-[calc(100vh-120px)] min-h-[520px]'
        )}
      >
        {/* Left: Das Cockpit (35%) */}
        <aside className="w-full lg:w-[35%] flex flex-col border-r border-gray-200 bg-white shrink-0">
          <div className="p-4 sm:p-5 border-b border-gray-100">
            <div className="flex rounded-lg bg-gray-100 p-0.5">
              <button
                type="button"
                onClick={() => setMode('new')}
                className={cn(
                  'flex-1 py-2 text-sm font-medium rounded-md transition-all tracking-tight',
                  mode === 'new' ? 'bg-white text-gray-900 shadow-sm' : 'text-gray-600 hover:text-gray-900'
                )}
              >
                Neue Mail
              </button>
              <button
                type="button"
                onClick={() => setMode('reply')}
                className={cn(
                  'flex-1 py-2 text-sm font-medium rounded-md transition-all tracking-tight',
                  mode === 'reply' ? 'bg-white text-gray-900 shadow-sm' : 'text-gray-600 hover:text-gray-900'
                )}
              >
                Antworten
              </button>
            </div>
          </div>

          <form
            ref={formRef}
            action={formAction}
            className="flex flex-col flex-1 min-h-0 overflow-y-auto"
          >
            <div className="p-4 sm:p-5 space-y-6">
              <AnimatePresence mode="wait">
                {mode === 'reply' ? (
                  <motion.div
                    key="reply"
                    initial={{ opacity: 0, y: 6 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -6 }}
                    transition={{ duration: 0.2 }}
                    className="space-y-3"
                  >
                    <label className="block text-sm font-medium text-gray-700 tracking-tight">
                      Erhaltene E-Mail hier einfügen
                    </label>
                    <textarea
                      name="receivedEmail"
                      value={receivedEmail}
                      onChange={(e) => setReceivedEmail(e.target.value)}
                      placeholder="E-Mail-Inhalt einfügen …"
                      className="w-full rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-orange-200 focus:border-orange-300 resize-none min-h-[140px] tracking-tight"
                      rows={5}
                    />
                  </motion.div>
                ) : null}
              </AnimatePresence>

              {/* Sektion A: Empfänger */}
              <div className="space-y-3">
                <div>
                  <label className="block text-sm font-medium text-gray-700 tracking-tight mb-2">
                    Wen schreibst du an? (Rolle/Beziehung)
                  </label>
                  <input
                    name="recipientRole"
                    type="text"
                    value={recipientRole}
                    onChange={(e) => setRecipientRole(e.target.value)}
                    placeholder="z.B. Vermieter, Mathelehrerin, Nachbar, Ex-Partner..."
                    className="w-full rounded-lg border border-gray-200 bg-gray-50 px-4 py-2.5 text-sm text-gray-900 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-orange-200 focus:border-orange-300 tracking-tight"
                  />
                </div>
                <div className="flex flex-wrap gap-2">
                  {QUICK_CHIPS.map((chip) => (
                    <button
                      key={chip.id}
                      type="button"
                      onClick={() => handleChipClick(chip.label)}
                      className="inline-flex items-center px-3 py-1.5 rounded-full text-xs font-medium bg-white border border-gray-200 text-gray-600 hover:bg-gray-50 hover:border-gray-300 transition-all tracking-tight"
                    >
                      {chip.label}
                    </button>
                  ))}
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-gray-500 uppercase tracking-wider mb-1.5">
                    Name Empfänger
                  </label>
                  <input
                    name="recipientName"
                    type="text"
                    value={recipientName}
                    onChange={(e) => setRecipientName(e.target.value)}
                    placeholder="z. B. Anna S."
                    className="w-full rounded-lg border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm text-gray-900 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-orange-200 focus:border-orange-300 tracking-tight"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-500 uppercase tracking-wider mb-1.5">
                    E-Mail <span className="font-normal normal-case text-gray-400">(opt.)</span>
                  </label>
                  <input
                    name="recipientEmail"
                    type="email"
                    value={recipientEmail}
                    onChange={(e) => setRecipientEmail(e.target.value)}
                    placeholder="anna@..."
                    className="w-full rounded-lg border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm text-gray-900 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-orange-200 focus:border-orange-300 tracking-tight"
                  />
                </div>
              </div>

              <div className="h-px bg-gray-100" />

              {/* Sektion B: Inhalt & Sprache */}
              <div className="space-y-3">
                <label className="block text-sm font-medium text-gray-700 tracking-tight">
                  Worum geht es?
                </label>
                <textarea
                  name="topic"
                  required
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder="Stichpunkte reichen (z. B. Heizung geht nicht, Frist bis morgen) …"
                  className="w-full rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-orange-200 focus:border-orange-300 resize-none min-h-[120px] tracking-tight"
                  rows={5}
                />
              </div>

              <div>
                <label className="block text-xs font-medium text-gray-500 uppercase tracking-wider mb-2">
                  Zielsprache der Mail
                </label>
                <select
                  name="language"
                  value={language}
                  onChange={(e) => setLanguage(e.target.value)}
                  className="w-full rounded-lg border border-gray-200 bg-white px-3 py-2.5 text-sm text-gray-900 focus:outline-none focus:ring-2 focus:ring-orange-200 focus:border-orange-300 tracking-tight"
                >
                  {LANGUAGES.map((lang) => (
                    <option key={lang} value={lang}>
                      {lang}
                    </option>
                  ))}
                </select>
              </div>

              <input name="senderName" type="hidden" value="" />
              <input name="tone" type="hidden" value="" />
              <input name="formality" type="hidden" value="" />
              <input name="length" type="hidden" value="Mittel" />
              <input name="workspaceId" type="hidden" value="" />

              <SubmitButton />

              {recipientRole && (
                <p className="text-xs text-gray-500 tracking-tight leading-relaxed">
                  <strong>Smart-Modus aktiv:</strong> Die AI analysiert "{recipientRole}" und passt Ton & Anrede automatisch an.
                </p>
              )}
            </div>

            {state?.error && (
              <p className="px-4 pb-4 text-sm text-red-600 tracking-tight">{state.error}</p>
            )}
          </form>
        </aside>

        {/* Right: Das Papier (65%) */}
        <main className="flex-1 min-w-0 flex flex-col bg-gray-50 lg:bg-gray-50/80">
          <div className="flex-1 overflow-auto p-4 sm:p-6 lg:p-8 flex items-start justify-center">
            {state?.result && !state.error && (state.result.includes('Premium') || state.result.includes('Freischalten')) ? (
              <motion.div
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, ease: 'easeOut' }}
                className="w-full max-w-2xl bg-white rounded-xl shadow-lg border border-gray-100 p-6 prose prose-sm max-w-none prose-p:text-gray-700 [&_a]:text-orange-600 [&_a]:underline"
              >
                <MarkdownRenderer content={state.result} />
              </motion.div>
            ) : state?.result && !state.error ? (
              <motion.div
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, ease: 'easeOut' }}
                className="w-full max-w-2xl bg-white rounded-xl shadow-lg border border-gray-100 overflow-hidden"
              >
                <div className="border-b border-gray-100 px-4 sm:px-6 py-3 bg-gray-50/50">
                  <label className="block text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">
                    Betreff
                  </label>
                  <input
                    value={editSubject}
                    onChange={(e) => setEditSubject(e.target.value)}
                    onBlur={syncResultFromEdits}
                    placeholder="✨ Betreff wird automatisch erstellt…"
                    className="w-full text-base font-semibold text-gray-900 bg-transparent border-0 focus:outline-none focus:ring-0 tracking-tight placeholder:text-gray-400 placeholder:font-normal"
                  />
                </div>
                <div className="px-4 sm:px-6 py-4 min-h-[220px]">
                  <label className="sr-only">E-Mail-Text</label>
                  <textarea
                    value={editBody}
                    onChange={(e) => setEditBody(e.target.value)}
                    onBlur={syncResultFromEdits}
                    className="w-full min-h-[200px] text-sm text-gray-700 bg-transparent border-0 focus:outline-none focus:ring-0 resize-none leading-relaxed tracking-tight"
                    placeholder="E-Mail-Text …"
                  />
                </div>
                <div className="border-t border-gray-100 px-4 sm:px-6 py-3 bg-gray-50/30 flex flex-col gap-3">
                  <div className="flex flex-wrap gap-2">
                    <button
                      type="button"
                      onClick={() => handleRefine('shorten')}
                      disabled={!!refineLoading}
                      className="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-medium text-gray-600 hover:bg-white transition-colors disabled:opacity-50 border border-gray-200"
                    >
                      {refineLoading === 'shorten' ? (
                        <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      ) : (
                        <Scissors className="w-3.5 h-3.5" />
                      )}
                      Zu lang? ✂️ Kürzen
                    </button>
                    <button
                      type="button"
                      onClick={() => handleRefine('loosen')}
                      disabled={!!refineLoading}
                      className="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-medium text-gray-600 hover:bg-white transition-colors disabled:opacity-50 border border-gray-200"
                    >
                      {refineLoading === 'loosen' ? (
                        <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      ) : (
                        <Smile className="w-3.5 h-3.5" />
                      )}
                      Zu steif? 😎 Lockerer
                    </button>
                    <button
                      type="button"
                      onClick={() => handleRefine('grammar')}
                      disabled={!!refineLoading}
                      className="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-medium text-gray-600 hover:bg-white transition-colors disabled:opacity-50 border border-gray-200"
                    >
                      {refineLoading === 'grammar' ? (
                        <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      ) : (
                        <Check className="w-3.5 h-3.5" />
                      )}
                      Grammatik-Check ✅
                    </button>
                  </div>
                  <div className="flex items-center gap-2">
                    <button
                      type="button"
                      onClick={handleCopy}
                      className="inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 transition-colors border border-gray-200"
                    >
                      <Copy className="w-4 h-4" />
                      Kopieren
                    </button>
                    <button
                      type="button"
                      onClick={handleGmail}
                      className="inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium text-white bg-gradient-to-r from-orange-500 to-pink-500 hover:from-orange-600 hover:to-pink-600 transition-all shadow-md"
                    >
                      <ExternalLink className="w-4 h-4" />
                      In Mail-App öffnen 🚀
                    </button>
                  </div>
                </div>
              </motion.div>
            ) : (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="w-full max-w-md flex flex-col items-center justify-center py-16 text-center"
              >
                <div className="w-14 h-14 rounded-full bg-gray-100 flex items-center justify-center mb-4">
                  <Mail className="w-7 h-7 text-gray-400" />
                </div>
                <p className="text-gray-500 font-medium tracking-tight">Das Papier</p>
                <p className="text-sm text-gray-400 mt-1 tracking-tight">
                  Deine E-Mail erscheint hier – klar, editierbar, bereit zum Versand.
                </p>
              </motion.div>
            )}
          </div>
        </main>
      </div>

      <AnimatePresence>
        {toast && (
          <motion.div
            key="toast"
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 px-4 py-2.5 rounded-xl bg-gray-900 text-white text-sm font-medium shadow-lg tracking-tight"
          >
            {toast}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
